import { collection, getDocs, doc, writeBatch, serverTimestamp, Timestamp } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Partner, UserProfile } from '../types';
import { seedDefaultCategories } from './categoryService';
import { logAuditEvent } from './auditService';

export const sampleTJPAPartners: Omit<Partner, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    fantasyName: 'Drogaria Extrafarma Belém',
    corporateName: 'Imifarma Produtos Farmacêuticos S.A.',
    personType: 'PJ',
    document: '04.899.316/0001-08',
    category: 'Saúde & Farmácias',
    address: 'Av. Nazaré, 450 - Nazaré',
    city: 'Belém',
    state: 'PA',
    description: 'Rede de farmácias com ampla cobertura na Região Metropolitana de Belém e interior do Pará.',
    contactName: 'Mariana Guimarães',
    contactRole: 'Gerente Comercial Regional',
    phone: '(91) 3214-5500',
    email: 'convenios.pa@extrafarma.com.br',
    website: 'www.extrafarma.com.br',
    socialMedia: '@extrafarma',
    origin: 'active_search',
    interestLevel: 'high',
    prospectingNotes: 'Parceiro com alto interesse em atender os magistrados e servidores do TJPA em todo o estado.',
    currentStage: 'approved',
    result: 'approved',
    processNumber: 'TJPA-ADM-2025/00142',
    officialPlatformUrl: 'https://www.tjpa.jus.br',
    submissionDate: new Date('2025-01-10T10:00:00'),
    analysisStartDate: new Date('2025-01-12T14:00:00'),
    decisionDate: new Date('2025-01-20T16:30:00'),
    acceptanceDate: new Date('2025-01-22T09:00:00'),
    partnershipStartDate: new Date('2025-02-01T00:00:00'),
    benefitDescription: 'Desconto de 15% a 35% em medicamentos de referência, genéricos e produtos de higiene pessoal.',
    discountPercentage: 25,
    targetAudience: 'Magistrados, Servidores, Dependentes e Estagiários',
    scope: 'statewide',
    conditions: 'Apresentação de crachá funcional ou declaração emitida pela SGP/TJPA no ato da compra.',
    assignedToName: 'Gestor Rede+',
    isArchived: false,
  },
  {
    fantasyName: 'Universidade da Amazônia - UNAMA',
    corporateName: 'Ser Educacional S.A.',
    personType: 'PJ',
    document: '02.408.016/0001-44',
    category: 'Educação & Ensino Superior',
    address: 'Av. Alcindo Cacela, 287 - Umarizal',
    city: 'Belém',
    state: 'PA',
    description: 'Instituição de ensino superior tradicional no Pará com cursos de graduação, pós-graduação e extensão.',
    contactName: 'Prof. Carlos Eduardo Mendes',
    contactRole: 'Diretor de Relações Institucionais',
    phone: '(91) 4009-3000',
    email: 'parcerias@unama.br',
    website: 'www.unama.br',
    socialMedia: '@unamaoficial',
    origin: 'spontaneous',
    interestLevel: 'high',
    prospectingNotes: 'Proposta de convênio para concessão de bolsas parciais em pós-graduação lato sensu em Direito e Gestão.',
    currentStage: 'in_analysis',
    processNumber: 'TJPA-ADM-2025/00289',
    submissionDate: new Date('2025-02-05T11:00:00'),
    analysisStartDate: new Date('2025-02-08T09:30:00'),
    benefitDescription: 'Desconto de 20% nas mensalidades de graduação e até 30% em cursos de especialização e MBA.',
    discountPercentage: 20,
    targetAudience: 'Servidores efetivos, comissionados e dependentes diretos',
    scope: 'statewide',
    conditions: 'Comprovação de vínculo funcional no momento da matrícula semestral.',
    assignedToName: 'Gestor Rede+',
    isArchived: false,
  },
  {
    fantasyName: 'Clínica Odontológica Sorriso Pará',
    corporateName: 'Sorriso Amazônia Odontologia Especializada Ltda',
    personType: 'PJ',
    document: '19.452.883/0001-20',
    category: 'Saúde & Farmácias',
    address: 'Tv. 14 de Março, 1120 - Nazaré',
    city: 'Belém',
    state: 'PA',
    description: 'Clínica multidisciplinar com tratamentos ortodônticos, implantodontia e estética dental.',
    contactName: 'Dra. Vanessa Lima',
    contactRole: 'Responsável Técnica',
    phone: '(91) 98112-4040',
    email: 'contato@sorrisopara.com.br',
    website: 'www.sorrisopara.com.br',
    socialMedia: '@sorrisopara',
    origin: 'indication',
    interestLevel: 'medium',
    prospectingNotes: 'Reunião virtual realizada. Solicitado envio dos documentos de regularidade fiscal e sanitária.',
    currentStage: 'waiting_docs',
    firstContactDate: new Date('2025-02-12T14:00:00'),
    nextContactDate: new Date(Date.now() + 86400000 * 3), // 3 days ahead
    benefitDescription: 'Tabela diferenciada com 20% de desconto em procedimentos estéticos e profilaxia gratuita anual.',
    discountPercentage: 20,
    targetAudience: 'Magistrados e Servidores do TJPA',
    scope: 'municipal',
    assignedToName: 'Gestor Rede+',
    isArchived: false,
  },
  {
    fantasyName: 'Academia Fit Pará Santarém',
    corporateName: 'Tapajós Fitness Centro de Treinamento Eireli',
    personType: 'PJ',
    document: '28.119.554/0001-99',
    category: 'Lazer, Esporte & Bem-estar',
    address: 'Av. Rui Barbosa, 620 - Centro',
    city: 'Santarém',
    state: 'PA',
    description: 'Centro de condicionamento físico, musculação e natação na Comarca de Santarém.',
    contactName: 'Rodrigo Alencar',
    contactRole: 'Proprietário',
    phone: '(93) 3522-8000',
    email: 'santarem@fitpara.com.br',
    origin: 'magistrate_request',
    interestLevel: 'high',
    prospectingNotes: 'Demanda apresentada por servidores do Polo Judiciário do Baixo Amazonas.',
    currentStage: 'prospecting',
    firstContactDate: new Date('2025-02-18T10:00:00'),
    nextContactDate: new Date(Date.now() + 86400000 * 1), // Tomorrow
    benefitDescription: 'Isenção de taxa de matrícula e 15% de desconto no plano livre mensal.',
    discountPercentage: 15,
    targetAudience: 'Servidores da Comarca de Santarém e região',
    scope: 'municipal',
    assignedToName: 'Gestor Rede+',
    isArchived: false,
  },
  {
    fantasyName: 'Livraria & Papelaria Fox Belém',
    corporateName: 'Fox Comércio de Livros e Material Escolar Ltda',
    personType: 'PJ',
    document: '05.334.887/0001-15',
    category: 'Cultura, Lazer & Livrarias',
    address: 'Tv. Dr. Moraes, 584 - Batista Campos',
    city: 'Belém',
    state: 'PA',
    description: 'Espaço cultural, cafeteria e livraria jurídica e geral.',
    contactName: 'Paula Siqueira',
    contactRole: 'Coordenadora de Eventos',
    phone: '(91) 4008-0007',
    email: 'eventos@foxbelem.com.br',
    website: 'www.foxbelem.com.br',
    origin: 'active_search',
    interestLevel: 'high',
    currentStage: 'mapped',
    firstContactDate: new Date('2025-02-20T15:00:00'),
    nextContactDate: new Date(Date.now() + 86400000 * 4),
    benefitDescription: 'Desconto de 10% a 15% em livros jurídicos e de literatura geral.',
    discountPercentage: 10,
    targetAudience: 'Todos os beneficiários do TJPA',
    scope: 'municipal',
    assignedToName: 'Gestor Rede+',
    isArchived: false,
  },
  {
    fantasyName: 'Hotel Princesa Louçã Belém',
    corporateName: 'Hotelaria Amazônica Princesa Ltda',
    personType: 'PJ',
    document: '07.994.221/0001-30',
    category: 'Turismo, Hotéis & Viagens',
    address: 'Av. Presidente Vargas, 882 - Campina',
    city: 'Belém',
    state: 'PA',
    description: 'Hotel central com infraestrutura para hospedagem e eventos corporativos.',
    contactName: 'Arthur Castilho',
    contactRole: 'Gerente Geral',
    phone: '(91) 4005-7700',
    email: 'comercial@hotelprincesa.com.br',
    website: 'www.hotelprincesa.com.br',
    origin: 'server_suggestion',
    interestLevel: 'medium',
    currentStage: 'approved',
    result: 'approved',
    processNumber: 'TJPA-ADM-2024/00889',
    decisionDate: new Date('2024-11-15T14:00:00'),
    acceptanceDate: new Date('2024-11-18T10:00:00'),
    partnershipStartDate: new Date('2024-12-01T00:00:00'),
    benefitDescription: 'Desconto de 20% na tarifa balcão de hospedagem para magistrados e servidores em trânsito.',
    discountPercentage: 20,
    targetAudience: 'Magistrados, servidores de todas as comarcas e familiares',
    scope: 'statewide',
    conditions: 'Reserva antecipada via canal corporativo com envio de identificação funcional.',
    assignedToName: 'Gestor Rede+',
    isArchived: false,
  },
];

export async function checkAndSeedInitialData(actingUser: { uid: string; displayName: string }) {
  try {
    const snap = await getDocs(collection(db, 'partners'));
    if (snap.empty) {
      console.log('Database empty. Seeding initial categories and TJPA partners...');
      await seedDefaultCategories(actingUser);

      const batch = writeBatch(db);
      for (const p of sampleTJPAPartners) {
        const partnerRef = doc(collection(db, 'partners'));
        batch.set(partnerRef, {
          ...p,
          submissionDate: p.submissionDate ? Timestamp.fromDate(p.submissionDate as Date) : null,
          analysisStartDate: p.analysisStartDate ? Timestamp.fromDate(p.analysisStartDate as Date) : null,
          decisionDate: p.decisionDate ? Timestamp.fromDate(p.decisionDate as Date) : null,
          acceptanceDate: p.acceptanceDate ? Timestamp.fromDate(p.acceptanceDate as Date) : null,
          partnershipStartDate: p.partnershipStartDate ? Timestamp.fromDate(p.partnershipStartDate as Date) : null,
          firstContactDate: p.firstContactDate ? Timestamp.fromDate(p.firstContactDate as Date) : null,
          nextContactDate: p.nextContactDate ? Timestamp.fromDate(p.nextContactDate as Date) : null,
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }
      await batch.commit();

      await logAuditEvent({
        action: 'system_seed_data',
        entityId: 'all',
        entityName: 'Banco de Demonstração TJPA',
        userUid: actingUser.uid,
        userName: actingUser.displayName,
        details: 'Carga inicial de dados e parceiros de teste do Programa Rede+ Vantagens TJPA.',
      });
    }
  } catch (err) {
    console.error('Failed to seed initial data:', err);
  }
}
